### ISSUE TITLE
Failed to pip3 install ores

### ISSUE THREAD

**Issue by ashish0910** [wikimedia/ores#286]
After entering the command in the terminal , following problem came up:

Downloading https://files.pythonhosted.org/packages/ea/50/43876eb63e4be9a71f1975d0196b57f0a02149182f751afc035d53c5f78d/ores-1.2.1-py2.py3-none-any.whl (897kB)
    2% |▊                               | 20kB 3.4kB/s eta 0:04:21Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
ashishs-MacBook-Air:~ ashishaggarwal$

**Comment by Ladsgroup** [comment]
Hello, thanks for the report but two notes: 1- The error says read timeout, it seems you have trouble connecting to pythonhosted.org or the website has issues. 2- iOS is not officially supported and I doubt it would even work.

**Comment by halfak** [comment]
If you're interested in working through some of the relevant issues, it would be nice to build some Mac OS instructions.  Let's see if you can get past the http issue first.  As @ladsgroup said, that seems to be related to your connection.

**Comment by ashish0910** [comment]
I was successfully able to overcome the http error . I am interested in working on the MacOS part as mentioned by @halfak . @Ladsgroup

**Comment by ashish0910** [comment]
After doing: pip install ores[redis] and running ores applications.wsgi

it shows the following error:

ashishs-MacBook-Air:~ ashishaggarwal$ ores applications.wsgi
2018-11-06 09:26:15,480 INFO:ores.applications.util -- Loading configs from []
Traceback (most recent call last):
  File "/anaconda3/bin/ores", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/ores/ores.py", line 57, in main
    module.main(sys.argv[2:])
  File "/anaconda3/lib/python3.6/site-packages/ores/applications/wsgi.py", line 45, in main
    config_dirs=args['--config-dir'])
  File "/anaconda3/lib/python3.6/site-packages/ores/applications/wsgi.py", line 49, in run
    application = build(**kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ores/applications/wsgi.py", line 56, in build
    config = build_config(**kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ores/applications/util.py", line 25, in build_config
    config = yamlconf.load(*(open(p) for fn, p in config_file_paths))
  File "/anaconda3/lib/python3.6/site-packages/yamlconf/load.py", line 22, in load
    raise errors.ConfigError("No config files provided.")
yamlconf.errors.ConfigError: No config files provided.

**Comment by halfak** [comment]
It looks like the --config-dir option's default is to search PWD/config/  If you don't have configuration in that location, you'll need to specify that parameter.

**Comment by Anand-Royy** [comment]
After entering the command I got this error. I tried to set it up on Ubuntu.
Please help me out @halfak .



ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l_hh1bjo/pyenchant/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l_hh1bjo/pyenchant/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-l_hh1bjo/pyenchant/pip-egg-info
         cwd: /tmp/pip-install-l_hh1bjo/pyenchant/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l_hh1bjo/pyenchant/setup.py", line 212, in <module>
        import enchant
      File "/tmp/pip-install-l_hh1bjo/pyenchant/enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "/tmp/pip-install-l_hh1bjo/pyenchant/enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
